/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package noobchain;

import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    @Test public void testBlockchain() {
        NoobChain.main(null);
        List<Block> blockchain = NoobChain.blockchain;
        assertEquals(blockchain.get(1).previousHash, blockchain.get(0).hash);
    }
}
